### ISSUE TITLE
gcp: Configure `google_organization_iam_policy `

### ISSUE THREAD

**Issue by donovanmuller** [upbound/provider-gcp#11]
### What resource do you need?

Provider Name: GCP
Terraform Resource Name: [`google_organization_iam_policy `](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_organization_iam#google_organization_iam_policy)

### What is your use case?

See this https://github.com/upbound/official-providers/pull/504#issuecomment-1222297858. `google_organization_iam_policy ` should be configured separately given the organisation level access required to test it.

**Comment by Pocokwins** [comment]
Hi, as my team is also interested in this feature, I'll open a PR to add `google_organization_iam_policy` resource in the upcoming days.

**Comment by jeanduplessis** [comment]
@Pocokwins please see https://github.com/upbound/provider-gcp/issues/14
We are considering not adding `*_iam_binding` and `*_iam_policy` resources in favor of only using `*_iam_member`.

Please add your use case there if this does not work for your team.

**Comment by Pocokwins** [comment]
> @Pocokwins please see #14 We are considering not adding `*_iam_binding` and `*_iam_policy` resources in favor of only using `*_iam_member`.
> 
> Please add your use case there if this does not work for your team.

Hi @jeanduplessis , thanks for the heads up. It looks like that the `google_organization_iam_member` will fit for our purposes as well.

**Comment by jeanduplessis** [comment]
Ok, that's great. The resource is available already: https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.28.0/resources/cloudplatform.gcp.upbound.io/OrganizationIAMMember/v1beta1

**Comment by jeanduplessis** [comment]
In the context of #14 I am closing this issue.
