### ISSUE TITLE
Request for the missing IAM policy for service account

### ISSUE THREAD

**Issue by ulucinar** [upbound/provider-gcp#110]
### What resource do you need?
Although we have `cloudplatform.ServiceAccount{,Key,IAMMember}` resources available in the provider, we are missing [IAM policy for service account](https://registry.terraform.io/providers/hashicorp/google/4.22.0/docs/resources/google_service_account_iam) resources.

Terraform Resource Name: 

We would like to configure and test:
`google_service_account_iam_policy`
`google_service_account_iam_binding`
`google_service_account_iam_member`

**Comment by sergenyalcin** [comment]
After the discussions with @ulucinar and the feedback from @AaronME, it seems that the `google_service_account_iam_member` resource is sufficient for the Crossplane use cases. And this resource is already generated in the provider-gcp. So, I am closing this issue.

For more read about dropping support the `*_iam_policy` and `*_iam_binding` resources please see https://github.com/upbound/provider-gcp/issues/14
