### ISSUE TITLE
Moving dataplex (1) resources to v1beta1 version

### ISSUE THREAD

**Issue by dverveiko** [upbound/provider-gcp#130]
Moving dataplex 1 resources to v1beta1 version

- [ ] [`google_dataplex_lake`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataplex_lake)

**Comment by MyzaTaras** [comment]
"make generate" - does not generate any resources.

**Comment by MyzaTaras** [comment]
Covered in https://github.com/upbound/provider-gcp/issues/176
