### ISSUE TITLE
Test resources with schema changes for v4.22.0 -> v4.48.0 version bump

### ISSUE THREAD

**Issue by ulucinar** [upbound/provider-gcp#137]
In the context of #63, we would like to test the following resources with Terraform state schema changes:
```
google_cloudbuild_trigger:1-2
```

And the following CRDs with breaking API changes:
```
cloudrun.gcp.upbound.io_services.yaml
compute.gcp.upbound.io_networkendpoints.yaml
container.gcp.upbound.io_clusters.yaml
container.gcp.upbound.io_nodepools.yaml
dns.gcp.upbound.io_recordsets.yaml
```

Known customer related resources:
`storage.Bucket`, `redis.Cloudmemorystoreinstance`, `sql.Cloudsqlinstance `

cc. @AaronME, @Piotr1215: It would be great to compile a list of resources that are internally employed so that we try to test them while bumping versions. Also, would you be willing to give a pre-release bumped provider-gcp a try in maybe a dev environment? We are also planning some e2e tests (please see https://github.com/upbound/team-extensions/issues/85).

**Comment by turkenf** [comment]
- `compute.gcp.upbound.io_networkendpoints.yaml`

```shell
NAME                                                 READY   SYNCED   EXTERNAL-NAME      AGE
subnetwork.compute.gcp.upbound.io/network-endpoint   True    True     network-endpoint   5m24s

NAME                                                      READY   SYNCED   EXTERNAL-NAME
                                     AGE
networkendpoint.compute.gcp.upbound.io/network-endpoint   True    True     official-provider-testing/us-central1-a/network-endp
oint/network-endpoint/10.2.0.21/90   5m24s

NAME                                                           READY   SYNCED   EXTERNAL-NAME      AGE
networkendpointgroup.compute.gcp.upbound.io/network-endpoint   True    True     network-endpoint   5m24s

NAME                                               READY   SYNCED   EXTERNAL-NAME      AGE
instance.compute.gcp.upbound.io/network-endpoint   True    True     network-endpoint   5m24s

NAME                                              READY   SYNCED   EXTERNAL-NAME      AGE
network.compute.gcp.upbound.io/network-endpoint   True    True     network-endpoint   5m24s
```

**Comment by AaronME** [comment]
@ulucinar I believe @turkenh raised the issue of using uptest for our internal resources. He was even kind enough to create a [demo PR](https://github.com/upbound/platform-composites/pull/86).

The effort is stalled because most of our composites are written to specifically support configuration within the "upbound cloud" ecosystem. We considered creating a "catch-all" composition that just contained one of each resource we use, however have not had time to devote to that effort.

(We are also still running terrajet providers, fwiw. Provider development is moving an impressive rate.)

**Comment by turkenf** [comment]
- `google_storage_bucket`

```shell
NAME                                                    READY   SYNCED   EXTERNAL-NAME             AGE
bucket.storage.gcp.upbound.io/bucket-fatih55deneme123   True    True     bucket-fatih55deneme123   27m
```

**Comment by turkenf** [comment]
We have successfully tested the above resources without making any changes to the example manifests and external name configurations.
