### ISSUE TITLE
Configure cloudplatform (17), cloudrun (5), cloudscheduler (1), cloudtasks (1), composer (1), compute (5)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-gcp#20]
External name configuration of 14 resources in the `cloudplatform` group:
* [`google_organization_iam_custom_role`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/organization_iam_custom_role)
* [`google_organization_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/organization_iam_member)
* [`google_organization_iam_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/organization_iam_policy)
* [`google_organization_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/organization_policy)
* [`google_project_default_service_accounts`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_default_service_accounts)
* [`google_project_iam_audit_config`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_iam_audit_config)
* [`google_project_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_iam_binding)
* [`google_project_iam_custom_role`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_iam_custom_role)
* [`google_project_iam_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_iam_policy)
* [`google_project_organization_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_organization_policy)
* [`google_project_service`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_service)
* [`google_project_usage_export_bucket`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_usage_export_bucket)
* [`google_service_account_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_account_iam_binding)
* [`google_service_networking_peered_dns_domain`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_networking_peered_dns_domain)

External name configuration of 5 resources in the `cloudrun` group:
* [`google_cloud_run_domain_mapping`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_domain_mapping)
* [`google_cloud_run_service`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service)
* [`google_cloud_run_service_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service_iam_binding)
* [`google_cloud_run_service_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service_iam_member)
* [`google_cloud_run_service_iam_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service_iam_policy)

External name configuration of 1 resources in the `cloudscheduler` group:
* [`google_cloud_scheduler_job`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job)

External name configuration of 1 resources in the `cloudtasks` group:
* [`google_cloud_tasks_queue`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_tasks_queue)

External name configuration of 1 resources in the `composer` group:
* [`google_composer_environment`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/composer_environment)

External name configuration of 5 resources in the `compute` group:
* [`google_compute_attached_disk`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_attached_disk)
* [`google_compute_autoscaler`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_autoscaler)
* [`google_compute_backend_bucket`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_bucket)
* [`google_compute_backend_bucket_signed_url_key`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_bucket_signed_url_key)
* [`google_compute_backend_service`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service)

**Comment by jeanduplessis** [comment]
I'm going to close this issue as we have another open issue for the remaining item.
