### ISSUE TITLE
Configure appengine (2), assuredworkloads (1), bigquery (15), bigtable (10), billing (2)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-gcp#22]
External name configuration of 2 resources in the `appengine` group:
* [`google_app_engine_service_split_traffic`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_service_split_traffic)
* [`google_app_engine_standard_app_version`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_standard_app_version)

External name configuration of 1 resources in the `assuredworkloads` group:
* [`google_assured_workloads_workload`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/assured_workloads_workload)

External name configuration of 15 resources in the `bigquery` group:
* [`google_bigquery_connection`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection)
* [`google_bigquery_data_transfer_config`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config)
* [`google_bigquery_dataset`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset)
* [`google_bigquery_dataset_access`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_access)
* [`google_bigquery_dataset_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam_binding)
* [`google_bigquery_dataset_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam_member)
* [`google_bigquery_dataset_iam_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam_policy)
* [`google_bigquery_job`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_job)
* [`google_bigquery_reservation`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_reservation)
* [`google_bigquery_reservation_assignment`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_reservation_assignment)
* [`google_bigquery_routine`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_routine)
* [`google_bigquery_table`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table)
* [`google_bigquery_table_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table_iam_binding)
* [`google_bigquery_table_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table_iam_member)
* [`google_bigquery_table_iam_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_table_iam_policy)

External name configuration of 10 resources in the `bigtable` group:
* [`google_bigtable_app_profile`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_app_profile)
* [`google_bigtable_gc_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_gc_policy)
* [`google_bigtable_instance`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance)
* [`google_bigtable_instance_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance_iam_binding)
* [`google_bigtable_instance_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance_iam_member)
* [`google_bigtable_instance_iam_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_instance_iam_policy)
* [`google_bigtable_table`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_table)
* [`google_bigtable_table_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_table_iam_binding)
* [`google_bigtable_table_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_table_iam_member)
* [`google_bigtable_table_iam_policy`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_table_iam_policy)

External name configuration of 2 resources in the `billing` group:
* [`google_billing_account_iam_binding`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_account_iam_binding)
* [`google_billing_account_iam_member`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_account_iam_member)

**Comment by voloshynivan** [comment]
Configurations described in the ticket are already done in scope  of other tickets: #91 and #56
