### ISSUE TITLE
Add DatabaseInstance Edition Field

### ISSUE THREAD

**Issue by snelsondexcom** [upbound/provider-gcp#372]
### What problem are you facing?

We'd like to be able to provision "Enterprise" editions for development environments and "Enterprise Plus" editions for production environments. Our current workaround is to create the instance without `provider-gcp`, selecting the preferred edition -- then we connect to the instance via a `DatabaseInstance` resource after the fact.

### How could Official GCP Provider help solve your problem?

Add an "edition" field to the "DatabaseInstance" resource.
e.g. https://cloud.google.com/sdk/gcloud/reference/sql/instances/create#--edition

**Comment by turkenf** [comment]
Hi @snelsondexcom,

Thank you for raising this issue, [edition parameter](https://github.com/upbound/provider-gcp/blob/b305a1cc1c470bbce8c1e9fe3bf83b829527fc8b/apis/sql/v1beta1/zz_databaseinstance_types.go#L1393C1-L1393C1) added to the main, please wait for the next release, scheduled for September 28, 2023

I'm closing this issue for now, feel free to reopen if you encounter any issues.
