### ISSUE TITLE
`enable_autopilot` conflicts with late init of `addons_config.gcs_fuse_csi_driver_config`

### ISSUE THREAD

**Issue by djeremiah** [upbound/provider-gcp#403]
### What happened?
on GCP, GKE autopilot clusters running k8s >= 1.24 now have the GCS Fuse driver addon enabled by default

This addon was previously unavailable for autopilot clusters and the terraform provider had a mutual exclusion check that you couldn't specify autopilot = true && GCS fuse driver = enabled

If you use the current latest GCP provider (0.37.0) to create a Cluster MR, with autopilot  enabled, and NO ADDON CONFIG provided, the cluster will provision successfully

The first time crossplane does a terraform refresh under the hood, it picks up that the GCS fuse addon is enabled (by default, by GCP) and then all subsequent refreshes fail with:

```
Not Synced
ReconcileError: observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "addons_config.0.gcs_fuse_csi_driver_config": conflicts with enable_autopilot
```

### How can we reproduce it?
Deploy `examples/container/cluster.yaml`

### What environment did it happen in?

* Crossplane Version: 1.13.2-up.2
* Provider Version: v0.37.0
* Kubernetes Version: 
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
* Kubernetes Distribution: kind

Relates to upbound/upjet#197

**Comment by vedantthapa** [comment]
I see that there's an open pull request to resolve this issue, in the meantime, are there any workarounds to provision gke autopilot clusters via crossplane?
