### ISSUE TITLE
Add support for new field on BigQuery connection: use_data_boost and database_role

### ISSUE THREAD

**Issue by afarbos** [upbound/provider-gcp#421]
### What problem are you facing?

I would like to use the feature available in the bigquery connection, see https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_connection#nested_cloud_spanner
However, I cannot find all the fields especially use_data_boost or database_role see https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.38.1/resources/bigquery.gcp.upbound.io/Connection/v1beta1#doc:spec-forProvider-cloudSpanner

### How could Official GCP Provider help solve your problem?

Add support for these fields

**Comment by turkenf** [comment]
Thank you for raising this @afarbos, I am closing this issue, these fields are available now: https://github.com/upbound/provider-gcp/blob/b0985987bbdab44094d32b7a040d246c14ad76a6/apis/bigquery/v1beta1/zz_connection_types.go#L278
