### ISSUE TITLE
Incorrect Sync status on Composition (XRC) level when managed resource failed to synced on lifecycle.prevent_destroy event

### ISSUE THREAD

**Issue by vitalybronshtein** [upbound/provider-gcp#437]
No indication on Claim ( XRC ) level that managed resource failed to synced on `immutable` fields 

For example when I'm update `machineType` in `NodePool` managed resource ( immutable filed ) , managed resource change status to `SYNCED=false` with `lifecycle.prevent_destroy error` , but no indication on XRC level that one of the resources failed to SYNCED , and claim status is `SYNCED=true`

- Manager resource event : 
```
Warning  CannotObserveExternalResource  14s (x6 over 52s)  managed/container.gcp.upbound.io/v1beta1, kind=nodepool  cannot run plan: plan failed: Instance cannot be destroyed: Resource google_container_node_pool.test-gke has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

- Managed resource status (SYNCED=False)
```
kubectl get nodepools.container.gcp.upbound.io
NAME              READY   SYNCED   EXTERNAL-NAME     AGE
test-gke   True    False    test-gke   98m
```

- Claim status (SYNCED=true):
```
kubectl get gkeclusters.cloud.crossplane.io
NAME              SYNCED   READY   COMPOSITION                                      AGE
test-gke   True     True    gkeclusters.cloud.crossplane.io   99m
```

What environment did it happen in?
Crossplane Version: v1.14.4
Provider Version: v0.38.0
Kubernetes Version: v1.25.200
Kubernetes Distribution: GKE

**Comment by jeanduplessis** [comment]
@vitalybronshtein the issue needs to be addressed upstream in Crossplane. I've opened an issue for this here: https://github.com/crossplane/crossplane/issues/5209
