### ISSUE TITLE
Request for `google_artifact_registry_repository`cleanup policy resource

### ISSUE THREAD

**Issue by cwichka** [upbound/provider-gcp#447]
### What resource do you need?

Terraform Resource Name: 
google_artifact_registry_repository_cleanup_policy

### What is your use case?
Configure cleanup policy for google artifacts to automatically delete artifact versions that you no longer need or keeping artifacts that you want to store indefinitely.

```[tasklist]
### Tasks
```

**Comment by turkenf** [comment]
@cwichka, thank you for bringing up this. As far as I understand, there is no new resource for this. I assume you want to use the [cleanup_policies](https://registry.terraform.io/providers/hashicorp/google/4.80.0/docs/resources/artifact_registry_repository#cleanup_policies) and [cleanup_policy_dry_run](https://registry.terraform.io/providers/hashicorp/google/4.80.0/docs/resources/artifact_registry_repository#cleanup_policy_dry_run) fields.

**Comment by cwichka** [comment]
Thanks @turkenf . 
Yes right, i was referring to those fields, my bad.

**Comment by turkenf** [comment]
I am closing this issue, these fields are available now: https://github.com/upbound/provider-gcp/blob/b0985987bbdab44094d32b7a040d246c14ad76a6/apis/artifact/v1beta1/zz_registryrepository_types.go#L403
