### ISSUE TITLE
Upgrade underlying GCP terraform provider

### ISSUE THREAD

**Issue by jeanduplessis** [upbound/provider-gcp#55]
### What problem are you facing?

The current Terraform provider is outdated.

### How could Official GCP Provider help solve your problem?
Upgrade to the latest Terraform provider for GCP to enable access to more resources and bug fixes

**Comment by ulucinar** [comment]
A PR has been opened in `upbound/provider-gcp` to reveal any early blockers:
https://github.com/upbound/provider-gcp/pull/63
