### ISSUE TITLE
Request for `google_iam_workload_identity_pool*` resources

### ISSUE THREAD

**Issue by aabouzaid** [upbound/provider-gcp#66]
### What resource do you need?

Terraform Resource Name: 
- [google_iam_workload_identity_pool](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iam_workload_identity_pool)
- [google_iam_workload_identity_pool_provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/iam_workload_identity_pool_provider)

### What is your use case?
I want to use configure GitHub Action auth to access GCP (GKE cluster). To do so, I need 2 things:
- Add a new GCP service account (available in Upbound GCP provider).
- Add a new GCP workload identity pool and provider (**missing** in Upbound GCP provider).

**Related docs:**
- GCP: [Manage workload identity pools and providers](https://cloud.google.com/iam/docs/manage-workload-identity-pools-providers)
- GitHub: [OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)

**Note:** The 2 requested resources are not mentioned in https://github.com/upbound/provider-gcp/issues/13

**Comment by jeanduplessis** [comment]
Adding these resources is blocked by https://github.com/upbound/provider-gcp/pull/63 as they aren't available in the current terraform version used in the provider. Once the PR lands, they can be added.

**Comment by jeanduplessis** [comment]
This issue is no longer blocked since we have landed #63.

**Comment by aabouzaid** [comment]
I see the 2 resources added (checked in v0.31.0: [WorkloadIdentityPool](https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.31.0/resources/iam.gcp.upbound.io/WorkloadIdentityPool/v1beta1), [WorkloadIdentityPoolProvider](https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.31.0/resources/iam.gcp.upbound.io/WorkloadIdentityPoolProvider/v1beta1)).

I didn't test them yet, but I will close this issue since they are already added.
