### ISSUE TITLE
Moving certificatemanager (3) resources to v1beta1 version

### ISSUE THREAD

**Issue by sergenyalcin** [upbound/provider-gcp#97]
Moving 3 resources to v1beta1 version

- [x] [google_certificate_manager_certificate](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/certificate_manager_certificate)
- [x] [google_certificate_manager_dns_authorization](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/certificate_manager_dns_authorization)
- [x] [google_certificate_manager_certificate_map_entry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/certificate_manager_certificate_map_entry)

**Comment by mykolalosev** [comment]
Looks like we don't have an approach for specific resources with required link field for the attached file.
Ex.: `pem_certificate = file("test-fixtures/certificatemanager/cert.pem")`
